project:
  type: book
  output-dir: docs

book:
  title: "R Programmierung"
  subtitle: "Ein praxisorientierter Einstieg in die Datenanalyse mit R für Bio- und Medizininformatik"
  author: "Beate Navarro Bullock"
  date: last-modified

  chapters:
    - index.qmd
    - chapters/01-einfuehrung.qmd
    - chapters/02-daten-repräsentieren.qmd
    - chapters/03-daten-transformieren.qmd

  search: true

format:
  html:
    toc: true
    theme: cosmo
    number-sections: true
    title-block-banner: figures/r-banner.png
    css: styles.css
