project:
  type: default
  output-dir: ../docs/slides
  resources: 
    - thi-logo.jpg

format:
  revealjs:
    theme: simple
    css: slides.css
    slide-number: c/t
    transition: none
    controls: true
    progress: false
    width: 1280
    height: 720
    margin: 0
    footer: "Einführung in R"
